# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezflC7DpvLrvBD4KjnQnbTFI1-Co_WST
"""

pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

# Konfigurasi Halaman
st.set_page_config(page_title="Personal AI Financial Coach", layout="wide")

# 1. DATA PREPARATION (Berdasarkan df_clean_summary yang kamu berikan)
# Kita gunakan nilai 'mean' sebagai profil default user
stats = {
    'Rent_Ratio': 0.2198,
    'Loan_Repayment_Ratio': 0.0434,
    'Insurance_Ratio': 0.0349,
    'Groceries_Ratio': 0.1253,
    'Transport_Ratio': 0.0650,
    'Eating_Out_Ratio': 0.0350,
    'Entertainment_Ratio': 0.0349,
    'Utilities_Ratio': 0.0602,
    'Healthcare_Ratio': 0.0399,
    'Education_Ratio': 0.0601,
    'Miscellaneous_Ratio': 0.0201,
    'Savings_Ratio': 0.2612
}

# Simulasi data 6 bulan terakhir agar Dashboard bisa menunjukkan "Konsistensi" (SMART 2)
np.random.seed(42)
history_months = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun"]
data_hist = []
for m in history_months:
    row = {k: v + np.random.uniform(-0.02, 0.02) for k, v in stats.items()}
    row['Month'] = m
    data_hist.append(row)
df_history = pd.DataFrame(data_hist)

# 2. SIDEBAR INPUT
st.sidebar.header("👤 Profil Finansial")
income = st.sidebar.number_input("Pendapatan Bulanan (Rp)", value=10000000, step=500000)
st.sidebar.divider()
st.sidebar.write("**Status Saat Ini:**")
st.sidebar.write(f"Rasio Tabungan: {stats['Savings_Ratio']*100:.1f}%")
st.sidebar.write(f"Rasio Kesehatan: {stats['Healthcare_Ratio']*100:.1f}%")

# 3. MAIN DASHBOARD
st.title("📊 Personal Financial SMART Strategy")
st.markdown(f"Selamat datang! Berdasarkan data Anda, rata-rata tabungan Anda berada di angka **{stats['Savings_Ratio']*100:.1f}%**.")

# ROW 1: KPI Metrics
c1, c2, c3, c4 = st.columns(4)
current_savings_val = stats['Savings_Ratio'] * income
lifestyle_val = (stats['Eating_Out_Ratio'] + stats['Entertainment_Ratio']) * income

c1.metric("Tabungan /Bulan", f"Rp {current_savings_val:,.0f}")
c2.metric("Biaya Hidup (Lifestyle)", f"Rp {lifestyle_val:,.0f}")
c3.metric("Rasio Sewa", f"{stats['Rent_Ratio']*100:.1f}%")
c4.metric("Rasio Kesehatan", f"{stats['Healthcare_Ratio']*100:.1f}%")

# TABS UNTUK STRATEGI SMART
tab1, tab2 = st.tabs(["🛡️ SMART 1: Dana Darurat", "📈 SMART 2: Konsistensi Tabungan"])

# --- TAB 1: DANA DARURAT (12 BULAN) ---
with tab1:
    st.subheader("Target: Membangun Dana Darurat 3x (Sewa + Cicilan)")

    # Perhitungan Logika
    monthly_fixed_cost_ratio = stats['Rent_Ratio'] + stats['Loan_Repayment_Ratio']
    monthly_fixed_cost_rp = monthly_fixed_cost_ratio * income
    target_emergency_fund = 3 * monthly_fixed_cost_rp

    # Berapa yang harus disisihkan dari tabungan saat ini?
    monthly_allocation = target_emergency_fund / 12

    col_a, col_b = st.columns([1, 2])
    with col_a:
        st.info(f"""
        **Rencana Aksi:**
        *   **Target Total:** Rp {target_emergency_fund:,.0f}
        *   **Alokasi Bulanan:** Rp {monthly_allocation:,.0f} /bulan
        *   **Healthcare Check:** ✅ Aman! Rasio Kesehatan Anda tetap di {stats['Healthcare_Ratio']*100:.1f}% tanpa gangguan.
        """)

        if monthly_allocation > current_savings_val:
            st.warning("⚠️ Alokasi dana darurat melebihi kemampuan menabung bulanan Anda. Pertimbangkan menekan biaya gaya hidup.")
        else:
            st.success("💪 Kemampuan menabung Anda cukup untuk mendanai target ini!")

    with col_b:
        # Proyeksi Pertumbuhan Dana Darurat
        months = np.arange(1, 13)
        accumulation = months * monthly_allocation
        fig_ef = px.area(x=months, y=accumulation,
                         title="Proyeksi 12 Bulan Dana Darurat",
                         labels={'x': 'Bulan Ke-', 'y': 'Total Saldo (Rp)'})
        st.plotly_chart(fig_ef, use_container_width=True)

# --- TAB 2: TARGET SAVINGS & LIFESTYLE CAP ---
with tab2:
    st.subheader("Target: Tabungan ≥ 20% & Lifestyle ≤ 5%")

    col_x, col_y = st.columns(2)

    with col_x:
        # Visualisasi Tren Historis (Konsistensi)
        fig_trend = px.line(df_history, x='Month', y='Savings_Ratio', markers=True,
                            title="Tren Rasio Tabungan 6 Bulan Terakhir")
        fig_trend.add_hline(y=0.20, line_dash="dash", line_color="green", annotation_text="Target 20%")
        st.plotly_chart(fig_trend, use_container_width=True)

        # Hitung Konsistensi
        consistent_months = len(df_history[df_history['Savings_Ratio'] >= 0.20])
        st.write(f"📊 **Skor Konsistensi:** {consistent_months}/6 Bulan di atas target.")

    with col_y:
        # Analisis Gaya Hidup
        current_lifestyle = stats['Eating_Out_Ratio'] + stats['Entertainment_Ratio']

        # Donut Chart untuk Gaya Hidup vs Lainnya
        labels = ['Gaya Hidup (Makan Luar + Ent)', 'Lain-lain']
        values = [current_lifestyle, 1 - current_lifestyle]

        fig_lifestyle = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.5)])
        fig_lifestyle.update_layout(title_text="Porsi Gaya Hidup Saat Ini")
        st.plotly_chart(fig_lifestyle, use_container_width=True)

        if current_lifestyle > 0.05:
            excess = current_lifestyle - 0.05
            st.error(f"⚠️ Biaya gaya hidup Anda ({current_lifestyle*100:.1f}%) melebihi batas SMART 5%. Perlu dikurangi sebesar Rp {excess*income:,.0f} per bulan.")
        else:
            st.success("✅ Hebat! Biaya gaya hidup Anda sudah sangat efisien (di bawah 5%).")

# FOOTER: Breakdown Seluruh Pengeluaran
st.divider()
st.subheader("🔍 Breakdown Alokasi Anggaran (Berdasarkan Nilai Rata-rata)")
all_stats = pd.DataFrame(list(stats.items()), columns=['Kategori', 'Rasio'])
all_stats['Nilai (Rp)'] = all_stats['Rasio'] * income
fig_all = px.bar(all_stats.sort_values('Nilai (Rp)'), x='Nilai (Rp)', y='Kategori', orientation='h',
                 color='Nilai (Rp)', color_continuous_scale='Viridis')
st.plotly_chart(fig_all, use_container_width=True)

st.caption("Data Scientist Note: Dashboard ini dikembangkan menggunakan analisis deskriptif dari df_clean_summary. Nilai historis disimulasikan untuk menunjukkan kapabilitas monitoring SMART.")
